services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    kordian.transcrify.test:
      class: Kordian\TranscrifyBundle\TranscrifyBundle\Service\testService
      abstract: true