services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  Kordian\TranscrifyBundle\Service\:
    resource: '../../src/Service/'

#  Kordian\TranscrifyBundle\:
#    resource: '../../../src/TranscrifyBundle/*'
#    exclude: '../../../src/TranscrifyBundle/{DependencyInjection,Tests}'