services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  Kordian\TranscrifyBundle\: ~

#  Kordian\TranscrifyBundle\:
#    resource: '../../../src/TranscrifyBundle/*'
#    exclude: '../../../src/TranscrifyBundle/{DependencyInjection,Tests}'